name: Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: npm install, build, and test
        run:
          npm install
          npm start
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "wahlhalla"
          entrypoint: "./server.js" 
