name: Deploy to Deta
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      - uses: BogDAAAMN/deta-deploy-action@v1.0.2
        with:
          deta-access-token: ${{ secrets.DETA_TOKEN }} 
          deta-name: 'wahlhalla'
          deta-project: 'Wahlhalla' 
